GET http://localhost:8080/interceptor

###
GET http://localhost:8080/modify_response


###
GET http://localhost:8080/user

###
GET http://localhost:8080/i18n?lang=zh_CN


###
GET http://localhost:8080/freemarker



###
GET http://localhost:8080/index


###
GET http://localhost:8080/xml


###
GET http://localhost:8080/master_list_user_demos


###
GET http://localhost:8080/slave_list_desks